language: java
jdk:
- openjdk11
addons:
  sonarcloud:
    organization: jhaloyn
    token: 03708fcc4b790afbaea2db1c03e9ef3338fe4ac3

script:

- mvn test sonar:sonar -Dsonar.projectKey=Jhaloyn_avro

#- mvn test -DfailIfNoTests=false -Dmaven.test.failure.ignore=true -Dtest=TestAvroMarshaller sonar:sonar -Dsonar.projectKey=Jhaloyn_avro



